### ISSUE TITLE
DNS does not resolve `.mesh` TLD when using the L2TP/IPsec VPN

### ISSUE THREAD

**Issue by meitar** [nycmeshnet/nycmesh-configs#1]
When [connected to the NYC Mesh network via L2TP/IPsec VPN as documented](https://docs.nycmesh.net/networking/vpnl2tpipsec/), I cannot resolve `.mesh` domains. I'm running macOS 10.13.6 High Sierra but I believe the issue is OS-agnostic. I've connected to the NYC Mesh VPN via the anonymous user account and received an IP address assignment on my `ppp0` interface:

```sh
$ ifconfig ppp0
ppp0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1280
        inet6 fe80::a65e:60ff:fef0:86bb%ppp0 prefixlen 64 scopeid 0xc 
        inet 10.70.72.94 --> 10.70.72.1 netmask 0xff000000 
        nd6 options=201<PERFORMNUD,DAD>
```

This assignment has successfully provided the `10.10.10.10` IP address as the NYC Mesh DNS server:

```sh
$ scutil --dns | head -n 9
DNS configuration

resolver #1
  nameserver[0] : 10.10.10.10
  if_index : 12 (ppp0)
  flags    : Supplemental, Request A records
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 100000
```

However, none of the domains in the current [`mesh.zone` file](https://github.com/nycmeshnet/nycmesh-dns/blob/354e9303285f3e18574239dbad0257a0399db83f/mesh.zone) seem to be accessible to me via this DNS server:

```sh
$ dig @10.10.10.10 dns.mesh

; <<>> DiG 9.10.6 <<>> @10.10.10.10 dns.mesh
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 40951
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dns.mesh.                      IN      A

;; AUTHORITY SECTION:
.                       86331   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2019082300 1800 900 604800 86400

;; Query time: 42 msec
;; SERVER: 10.10.10.10#53(10.10.10.10)
;; WHEN: Fri Aug 23 03:18:45 EDT 2019
;; MSG SIZE  rcvd: 112
```

Notice the `NXDOMAIN` error code in response.

Note that the public `*.mesh.nycmesh.net` mirror does work and correctly resolves domains in the `.mesh` TLD regardless of whether I am connected to the NYC Mesh VPN or not:

```sh
$ dig @8.8.8.8 dns.mesh.nycmesh.net +short
10.10.10.10
```

I have further verified that the DNS query is traveling to the VPN endpoint via `tcpdump` packet capture:

```sh
$ tcpdump -i ppp0 -n udp port 53
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ppp0, link-type PPP (PPP), capture size 262144 bytes
03:22:57.434234 IP 10.70.72.94.54191 > 10.10.10.10.53: 22689+ [1au] A? dns.mesh. (37)
03:22:57.469209 IP 10.10.10.10.53 > 10.70.72.94.54191: 22689 NXDomain 0/1/1 (112)
^C
2 packets captured
2 packets received by filter
0 packets dropped by kernel
```

So it seems that the `.mesh` TLD is simply not being resolved at all, at least for L2TP/IPsec VPN users?

As an aside, I am unsure if this is the correct place to report this apparent bug. I would have added an issue to the [`nycmesh-dns` repository](https://github.com/nycmeshnet/nycmesh-dns), but it does not have GitHub issue tracking enabled.

**Comment by zgiles** [comment]
Thanks for the detailed information. The tcpdump as well is appreciated. 
Kindof interesting.. I was able to perform the above from my computer on the mesh (also over VPN, but a VPNed node ) and it worked. Perhaps it's a caching problem on the DNS Side..

```
$ nslookup
> server 10.10.10.10
Default server: 10.10.10.10
Address: 10.10.10.10#53
> unms.mesh
Server:		10.10.10.10
Address:	10.10.10.10#53

Non-authoritative answer:
Name:	unms.mesh
Address: 10.70.76.21
> dns.mesh
Server:		10.10.10.10
Address:	10.10.10.10#53

Non-authoritative answer:
Name:	dns.mesh
Address: 10.10.10.10
> 
```
```
$ dig @10.10.10.10 dns.mesh

; <<>> DiG 9.11.6-P1-RedHat-9.11.6-5.P1.fc30 <<>> @10.10.10.10 dns.mesh
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21727
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dns.mesh.			IN	A

;; ANSWER SECTION:
dns.mesh.		3584	IN	A	10.10.10.10

;; Query time: 6 msec
;; SERVER: 10.10.10.10#53(10.10.10.10)
;; WHEN: Sat Aug 24 17:38:07 EDT 2019
;; MSG SIZE  rcvd: 53

```

**Comment by meitar** [comment]
Huh. I originally posted this issue because I had been trying for almost two days and did not get `.mesh` DNS resolution to work, but I tried just now while connected to the NYC Mesh VPN through a non-Mesh node, and it works fine. `¯\_(ツ)_/¯`

Thanks for the prompt reply, regardless.
