### ISSUE TITLE
Add LR config

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmesh-configs#10]
Can we add LR to the generator? We've had a lot of problems because the gen2 config isn't compatible with the LR. 

Here's a link to a good LR config file that just needs node number input- 
https://docs.nycmesh.net/download/lbe-LR.cfg

**Comment by OlivierMorf** [comment]
Wondering if we need a different process for the Lbe.  I looked at the conf. for the standar lbe v8.7.1  and it seems there are other "lines" in the code, than in the 8.5.7 template in use now. I wonder if that can be an issue ? 
I would think we need a config. per lbe firmware. no ?
