### ISSUE TITLE
sn1 config still shows, even after deleting it

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmesh-configs#3]
I deleted the obsolete SN1 litebeam config, but configgen is still showing it

**Comment by zgiles** [comment]
BTW, moved this issue to 'configs' instead of 'configgen'. One is the configs, the other is the website that loads the config.
This was solved by #2. configgen isnt on master it's on tags and branches, so the change didnt show up. Added to beta and v4.3
