### ISSUE TITLE
SXTsq solo config doesn't work in routeros-arm-6.46.4.npk

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmesh-configs#4]
The solo config works in older routeros but not the new stable 6.46.4

Robj suggested a workaround by adding `installation=any` before `frequency=5180` . I tested this and it worked. I guess we should add this to all SXTsq configs.

_robj  2 days ago
The extra lines are specifically
installation=any
before the
frequency=5180 line (edited)_

**Comment by zgiles** [comment]
This is added in the `beta` branch, to come out in v4.4 shortly.

**Comment by bhny** [comment]
Zach, this was never added. It's a huge problem and caused a few aborted installs

**Comment by bhny** [comment]
ah, I see Olivier added it

**Comment by OlivierMorf** [comment]
added to v.4.5-beta.1  and we now use Omni v6.48. Closing this "Issue"
(added in sxt-wds-ospf  and sxt-wds-ospf-solo,   not sure it is required in the kiosk vpn version as we do not fix the freq. but scan the band).
installation=any was added to the Omni conf. in an earlier version.
